// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data/imss.proto

package data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UploadStatus int32

const (
	UploadStatus_UNKNOWN     UploadStatus = 0
	UploadStatus_IN_PROGRESS UploadStatus = 1
	UploadStatus_DONE        UploadStatus = 2
	UploadStatus_ERROR       UploadStatus = 3
)

var UploadStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "IN_PROGRESS",
	2: "DONE",
	3: "ERROR",
}

var UploadStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"IN_PROGRESS": 1,
	"DONE":        2,
	"ERROR":       3,
}

func (x UploadStatus) String() string {
	return proto.EnumName(UploadStatus_name, int32(x))
}

func (UploadStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a58d1631f7553e27, []int{0}
}

type Session struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Active               bool                 `protobuf:"varint,2,opt,name=active,proto3" json:"active,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	FinishedAt           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	Name                 string               `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Images               []*Image             `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_a58d1631f7553e27, []int{0}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Session) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Session) GetFinishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FinishedAt
	}
	return nil
}

func (m *Session) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Session) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

type Image struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId            string               `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	LocalPath            string               `protobuf:"bytes,3,opt,name=localPath,proto3" json:"localPath,omitempty"`
	CloudId              string               `protobuf:"bytes,4,opt,name=cloudId,proto3" json:"cloudId,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Size                 uint64               `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_a58d1631f7553e27, []int{1}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Image) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *Image) GetLocalPath() string {
	if m != nil {
		return m.LocalPath
	}
	return ""
}

func (m *Image) GetCloudId() string {
	if m != nil {
		return m.CloudId
	}
	return ""
}

func (m *Image) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Image) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ImageUpload struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobId                string       `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	ImageId              string       `protobuf:"bytes,3,opt,name=imageId,proto3" json:"imageId,omitempty"`
	Progress             uint64       `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Status               UploadStatus `protobuf:"varint,5,opt,name=status,proto3,enum=imss.UploadStatus" json:"status,omitempty"`
	Error                *Error       `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ImageUpload) Reset()         { *m = ImageUpload{} }
func (m *ImageUpload) String() string { return proto.CompactTextString(m) }
func (*ImageUpload) ProtoMessage()    {}
func (*ImageUpload) Descriptor() ([]byte, []int) {
	return fileDescriptor_a58d1631f7553e27, []int{2}
}

func (m *ImageUpload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageUpload.Unmarshal(m, b)
}
func (m *ImageUpload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageUpload.Marshal(b, m, deterministic)
}
func (m *ImageUpload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageUpload.Merge(m, src)
}
func (m *ImageUpload) XXX_Size() int {
	return xxx_messageInfo_ImageUpload.Size(m)
}
func (m *ImageUpload) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageUpload.DiscardUnknown(m)
}

var xxx_messageInfo_ImageUpload proto.InternalMessageInfo

func (m *ImageUpload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ImageUpload) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ImageUpload) GetImageId() string {
	if m != nil {
		return m.ImageId
	}
	return ""
}

func (m *ImageUpload) GetProgress() uint64 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *ImageUpload) GetStatus() UploadStatus {
	if m != nil {
		return m.Status
	}
	return UploadStatus_UNKNOWN
}

func (m *ImageUpload) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type UploadJob struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageIds             []string             `protobuf:"bytes,2,rep,name=imageIds,proto3" json:"imageIds,omitempty"`
	Status               UploadStatus         `protobuf:"varint,3,opt,name=status,proto3,enum=imss.UploadStatus" json:"status,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	FinishedAt           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=finishedAt,proto3" json:"finishedAt,omitempty"`
	Progress             uint64               `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	Size                 uint64               `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Recipient            string               `protobuf:"bytes,8,opt,name=recipient,proto3" json:"recipient,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UploadJob) Reset()         { *m = UploadJob{} }
func (m *UploadJob) String() string { return proto.CompactTextString(m) }
func (*UploadJob) ProtoMessage()    {}
func (*UploadJob) Descriptor() ([]byte, []int) {
	return fileDescriptor_a58d1631f7553e27, []int{3}
}

func (m *UploadJob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadJob.Unmarshal(m, b)
}
func (m *UploadJob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadJob.Marshal(b, m, deterministic)
}
func (m *UploadJob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadJob.Merge(m, src)
}
func (m *UploadJob) XXX_Size() int {
	return xxx_messageInfo_UploadJob.Size(m)
}
func (m *UploadJob) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadJob.DiscardUnknown(m)
}

var xxx_messageInfo_UploadJob proto.InternalMessageInfo

func (m *UploadJob) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UploadJob) GetImageIds() []string {
	if m != nil {
		return m.ImageIds
	}
	return nil
}

func (m *UploadJob) GetStatus() UploadStatus {
	if m != nil {
		return m.Status
	}
	return UploadStatus_UNKNOWN
}

func (m *UploadJob) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UploadJob) GetFinishedAt() *timestamp.Timestamp {
	if m != nil {
		return m.FinishedAt
	}
	return nil
}

func (m *UploadJob) GetProgress() uint64 {
	if m != nil {
		return m.Progress
	}
	return 0
}

func (m *UploadJob) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *UploadJob) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

type Error struct {
	Code                 uint64   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_a58d1631f7553e27, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() uint64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("imss.UploadStatus", UploadStatus_name, UploadStatus_value)
	proto.RegisterType((*Session)(nil), "imss.Session")
	proto.RegisterType((*Image)(nil), "imss.Image")
	proto.RegisterType((*ImageUpload)(nil), "imss.ImageUpload")
	proto.RegisterType((*UploadJob)(nil), "imss.UploadJob")
	proto.RegisterType((*Error)(nil), "imss.Error")
}

func init() {
	proto.RegisterFile("data/imss.proto", fileDescriptor_a58d1631f7553e27)
}

var fileDescriptor_a58d1631f7553e27 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0x36, 0x69, 0x92, 0x36, 0x13, 0xb9, 0x2b, 0x8b, 0x48, 0x28, 0x07, 0xc6, 0xfa, 0x12, 0xee,
	0x21, 0x85, 0x8a, 0x20, 0xbe, 0x9d, 0x58, 0xa4, 0x0a, 0xed, 0xb1, 0xf5, 0x10, 0x7c, 0x91, 0x4d,
	0x76, 0x2f, 0x5d, 0x69, 0xb2, 0x25, 0xbb, 0xf5, 0xc1, 0x3f, 0xe4, 0x5f, 0x10, 0xfc, 0x33, 0xfe,
	0x14, 0xc9, 0x24, 0x69, 0x7b, 0xf6, 0xe1, 0x38, 0xdf, 0x76, 0xbe, 0x99, 0x61, 0xbe, 0xef, 0x9b,
	0x61, 0xe1, 0x9c, 0x33, 0xc3, 0x26, 0xb2, 0xd0, 0x3a, 0xd9, 0x56, 0xca, 0x28, 0xe2, 0xd4, 0xef,
	0xd1, 0xb3, 0x5c, 0xa9, 0x7c, 0x23, 0x26, 0x88, 0xa5, 0xbb, 0xdb, 0x89, 0x91, 0x85, 0xd0, 0x86,
	0x15, 0xdb, 0xa6, 0x6c, 0xfc, 0xc7, 0x82, 0xfe, 0x4a, 0x68, 0x2d, 0x55, 0x49, 0xce, 0xc0, 0x96,
	0x3c, 0xb4, 0x22, 0x2b, 0xf6, 0xa9, 0x2d, 0x39, 0x79, 0x0a, 0x1e, 0xcb, 0x8c, 0xfc, 0x2e, 0x42,
	0x3b, 0xb2, 0xe2, 0x01, 0x6d, 0x23, 0xf2, 0x1a, 0xfc, 0xac, 0x12, 0xcc, 0x08, 0x7e, 0x65, 0xc2,
	0x5e, 0x64, 0xc5, 0xc1, 0x74, 0x94, 0x34, 0x83, 0x92, 0x6e, 0x50, 0xf2, 0xa9, 0x1b, 0x44, 0x0f,
	0xc5, 0xe4, 0x0d, 0xc0, 0xad, 0x2c, 0xa5, 0x5e, 0x63, 0xab, 0x73, 0x6f, 0xeb, 0x51, 0x35, 0x21,
	0xe0, 0x94, 0xac, 0x10, 0xa1, 0x8b, 0xfc, 0xf0, 0x4d, 0x5e, 0x80, 0x27, 0x0b, 0x96, 0x0b, 0x1d,
	0x7a, 0x51, 0x2f, 0x0e, 0xa6, 0x41, 0x82, 0x0e, 0xcc, 0x6b, 0x8c, 0xb6, 0xa9, 0xf1, 0x6f, 0x0b,
	0x5c, 0x44, 0x4e, 0x04, 0x5e, 0x80, 0xaf, 0x1b, 0xed, 0x73, 0x8e, 0x1a, 0x7d, 0x7a, 0x00, 0xea,
	0xec, 0x46, 0x65, 0x6c, 0x73, 0xcd, 0xcc, 0x1a, 0x65, 0xfa, 0xf4, 0x00, 0x90, 0x10, 0xfa, 0xd9,
	0x46, 0xed, 0xf8, 0x9c, 0xa3, 0x0e, 0x9f, 0x76, 0xe1, 0x5d, 0x7b, 0xdc, 0x87, 0xd8, 0x43, 0xc0,
	0xd1, 0xf2, 0x87, 0x08, 0xbd, 0xc8, 0x8a, 0x1d, 0x8a, 0xef, 0xf1, 0x2f, 0x0b, 0x02, 0x64, 0x7f,
	0xb3, 0xdd, 0x28, 0xc6, 0x4f, 0x34, 0x3c, 0x01, 0xf7, 0x9b, 0x4a, 0xf7, 0xfc, 0x9b, 0xa0, 0x66,
	0x87, 0xea, 0xe7, 0xbc, 0x65, 0xde, 0x85, 0x64, 0x04, 0x83, 0x6d, 0xa5, 0xf2, 0x4a, 0x68, 0x8d,
	0xc4, 0x1d, 0xba, 0x8f, 0xc9, 0x25, 0x78, 0xda, 0x30, 0xb3, 0xd3, 0x48, 0xfb, 0x6c, 0x4a, 0x1a,
	0x3b, 0x9b, 0xc9, 0x2b, 0xcc, 0xd0, 0xb6, 0x82, 0x3c, 0x07, 0x57, 0x54, 0x95, 0xaa, 0x90, 0xec,
	0xde, 0xf9, 0x59, 0x0d, 0xd1, 0x26, 0x33, 0xfe, 0x69, 0x83, 0xdf, 0xf4, 0x7e, 0x50, 0xe9, 0x09,
	0xf1, 0x11, 0x0c, 0x5a, 0x4e, 0x3a, 0xb4, 0xa3, 0x5e, 0xec, 0xd3, 0x7d, 0x7c, 0x44, 0xa4, 0x77,
	0x2f, 0x91, 0x3b, 0x76, 0x3b, 0xff, 0x7f, 0x8d, 0xee, 0x83, 0xae, 0xf1, 0xd8, 0x46, 0xef, 0x1f,
	0x1b, 0xbb, 0x35, 0xf6, 0x0f, 0x6b, 0xac, 0x8f, 0xa9, 0x12, 0x99, 0xdc, 0x4a, 0x51, 0x9a, 0x70,
	0xd0, 0x1c, 0xd3, 0x1e, 0x18, 0xbf, 0x02, 0x17, 0x9d, 0xab, 0x5b, 0x33, 0xc5, 0x05, 0xda, 0xe4,
	0x50, 0x7c, 0xd7, 0xbb, 0x2c, 0x84, 0xd6, 0x2c, 0x17, 0xed, 0x8e, 0xbb, 0xf0, 0xf2, 0x0a, 0x1e,
	0x1f, 0x5b, 0x42, 0x02, 0xe8, 0xdf, 0x2c, 0x3e, 0x2e, 0x96, 0x9f, 0x17, 0xc3, 0x47, 0xe4, 0x1c,
	0x82, 0xf9, 0xe2, 0xeb, 0x35, 0x5d, 0xbe, 0xa7, 0xb3, 0xd5, 0x6a, 0x68, 0x91, 0x01, 0x38, 0xef,
	0x96, 0x8b, 0xd9, 0xd0, 0x26, 0x3e, 0xb8, 0x33, 0x4a, 0x97, 0x74, 0xd8, 0x7b, 0x7b, 0xf1, 0x65,
	0x94, 0x4b, 0xb3, 0xde, 0xa5, 0x49, 0xa6, 0x8a, 0x49, 0xba, 0x2b, 0x65, 0x89, 0xbf, 0xc8, 0xa4,
	0xfe, 0x4f, 0x52, 0x0f, 0x5d, 0x78, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xda, 0xe6, 0x34, 0x81,
	0x5e, 0x04, 0x00, 0x00,
}
