// Code generated by qtc from "text.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// Message prints a page implementing Message interface.
//

//line mail/text.qtpl:3
package mail

//line mail/text.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line mail/text.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line mail/text.qtpl:3
func StreamText(qw422016 *qt422016.Writer, name string, link string) {
//line mail/text.qtpl:3
	qw422016.N().S(`
Hi there,
There is your `)
//line mail/text.qtpl:5
	qw422016.E().S(name)
//line mail/text.qtpl:5
	qw422016.N().S(`: `)
//line mail/text.qtpl:5
	qw422016.E().S(link)
//line mail/text.qtpl:5
	qw422016.N().S(`
`)
//line mail/text.qtpl:6
}

//line mail/text.qtpl:6
func WriteText(qq422016 qtio422016.Writer, name string, link string) {
//line mail/text.qtpl:6
	qw422016 := qt422016.AcquireWriter(qq422016)
//line mail/text.qtpl:6
	StreamText(qw422016, name, link)
//line mail/text.qtpl:6
	qt422016.ReleaseWriter(qw422016)
//line mail/text.qtpl:6
}

//line mail/text.qtpl:6
func Text(name string, link string) string {
//line mail/text.qtpl:6
	qb422016 := qt422016.AcquireByteBuffer()
//line mail/text.qtpl:6
	WriteText(qb422016, name, link)
//line mail/text.qtpl:6
	qs422016 := string(qb422016.B)
//line mail/text.qtpl:6
	qt422016.ReleaseByteBuffer(qb422016)
//line mail/text.qtpl:6
	return qs422016
//line mail/text.qtpl:6
}
